plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bigsinger.tvinstaller'
    compileSdk 34

    defaultConfig {
        applicationId 'com.bigsinger.tvinstaller'
        minSdk 17
        targetSdk 34
        versionCode 1
        versionName '1.0.0'
        multiDexEnabled true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'eu.agno3.jcifs:jcifs-ng:2.1.8'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.core:core:1.9.0'
    implementation 'androidx.leanback:leanback:1.0.0'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
}
